language: go

go:
- "1.9"
- "1.10"

go_import_path: github.com/lz006/extended-awx-client-go

install:
- go get github.com/golang/glog
- go get golang.org/x/tools/cmd/goimports
- go get github.com/seborama/govcr

script:
- make verify
- go build ./eawx
- for i in examples/*.go; do go build "${i}"; done
- go test ./eawx